version: 2.1
jobs:
  run-python27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python python/pi.py
      - run: python python/pi-decimal.py
  run-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python python/pi.py
      - run: python python/pi-decimal.py
  run-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python python/pi.py
      - run: python python/pi-decimal.py
  run-python38:
    docker:
      - image: circleci/python:3.8-rc
    steps:
      - checkout
      - run: python python/pi.py
      - run: python python/pi-decimal.py
  run-php5:
    docker:
      - image: circleci/php:5
    steps:
      - checkout
      - run: php php/pi.php
  run-php7:
    docker:
      - image: circleci/php:7
    steps:
      - checkout
      - run: php php/pi.php

workflows:
  version: 2.1
  build:
    jobs:
      - run-python27
      - run-python36
      - run-python37
      - run-python38 
      - run-php5
      - run-php7
