version: 2.1
jobs:
  run-python27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python python/pi.py > /tmp/python2.7-pi.txt
      - run: python python/pi-decimal.py > /tmp/python2.7-pi-decimal.txt
      - store_test_results:
          path: /tmp/python2.7-pi.txt
      - store_test_results:
          path: /tmp/python2.7-pi-decimal.txt
  run-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python python/pi.py > /tmp/python3.6-pi.txt
      - run: python python/pi-decimal.py > /tmp/python3.6-pi-decimal.txt
      - store_test_results:
          path: /tmp/python3.6-pi.txt
      - store_test_results:
          path: /tmp/python3.6-pi-decimal.txt
  run-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: python python/pi.py > /tmp/python3.7-pi.txt
      - run: python python/pi-decimal.py > /tmp/python3.7-pi-decimal.txt
      - store_test_results:
          path: /tmp/python3.7-pi.txt
      - store_test_results:
          path: /tmp/python3.7-pi-decimal.txt
  run-python38:
    docker:
      - image: circleci/python:3.8-rc
    steps:
      - checkout
      - run: python python/pi.py > /tmp/python3.8-pi.txt
      - run: python python/pi-decimal.py > /tmp/python3.8-pi-decimal.txt
      - store_test_results:
          path: /tmp/python3.8-pi.txt
      - store_test_results:
          path: /tmp/python3.8-pi-decimal.txt
  run-php5:
    docker:
      - image: circleci/php:5
    steps:
      - checkout
      - run: php php/pi.php > /tmp/php5-pi.txt
      - store_test_results:
          path: /tmp/php5-pi.txt
  run-php7:
    docker:
      - image: circleci/php:7
    steps:
      - checkout
      - run: php php/pi.php > /tmp/php7-pi.txt
      - store_test_results:
          path: /tmp/php7-pi.txt

workflows:
  version: 2.1
  build:
    jobs:
      - run-python27
      - run-python36
      - run-python37
      - run-python38 
      - run-php5
      - run-php7
