version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run calculator
          command: |
            python python/pi.py
            python3 python/pi.py
